[account]
account  = "account-1234"
authenticator = "externalbrowser"
user     = "ms@example.com"
password = "123456"
role     = "ROLE_DEVELOPER"
database = "DB_RESEARCHER"
schema = "MS_SCHEMA"
warehouse = "WAREHOUSE_WH_XL"
